spring:
  application:
    name: springboot

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_vendor
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
